import { EventEmitter } from '@angular/core';
import { GridBaseComponent } from '../gridbase/grid-base.component';
import { GroupTemplateDirective, DetailTemplateDirective } from '../base/template-base';
export declare const DATAGRID_TEMPLATE: string;
export declare class DataGridComponent extends GridBaseComponent {
    groupTemplate: GroupTemplateDirective;
    detailTemplate: DetailTemplateDirective;
    rowCss: any;
    idField: string;
    groupField: string;
    expanderWidth: number;
    editMode: string;
    clickToEdit: boolean;
    dblclickToEdit: boolean;
    rowDblClick: EventEmitter<{}>;
    cellDblClick: EventEmitter<{}>;
    rowContextMenu: EventEmitter<{}>;
    cellContextMenu: EventEmitter<{}>;
    rowExpand: EventEmitter<{}>;
    rowCollapse: EventEmitter<{}>;
    groupExpand: EventEmitter<{}>;
    groupCollapse: EventEmitter<{}>;
    editBegin: EventEmitter<{}>;
    editEnd: EventEmitter<{}>;
    editCancel: EventEmitter<{}>;
    groupData: any[];
    expandedRows: any[];
    editingItem: any;
    setData(value: any[]): void;
    ngAfterViewInit(): void;
    updateFrozenView(scrollTop: number, rows: any[]): void;
    onBodyScroll(event: any): void;
    getRowIndex(row: any): any;
    getAbsoluteIndex(index: number): any;
    scrollTo(row: any): void;
    sortData(): void;
    isGroupRow(row: any): boolean;
    isGrouped(data: any): boolean;
    getGroup(value: any, groups?: any[]): any;
    makeGroup(data: any[]): any[];
    makeGroupedRows(): any[];
    collapseGroup(value: any): void;
    expandGroup(value: any): void;
    toggleGroup(value: any): void;
    getExpandedIndex(row: any): number;
    isRowExpanded(row: any): boolean;
    collapseRow(row: any): void;
    expandRow(row: any): void;
    toggleRow(row: any): void;
    isEditing(row: any, column?: any): boolean;
    beginEdit(row: any, column?: any, rowEl?: any): void;
    endEdit(): void;
    cancelEdit(): void;
}
