import { ElementRef } from '@angular/core';
import { DataGridComponent } from './datagrid.component';
import { DataGridBodyComponent } from './datagrid-body.component';
export declare class DataGridTableComponent {
    gridBody: DataGridBodyComponent;
    groupTitleRef: ElementRef;
    columns: any;
    rows: any;
    grid: DataGridComponent;
    readonly showExpandIcon: boolean;
    readonly groupTitleWidth: any;
    readonly titleLeft: number;
    constructor(gridBody: DataGridBodyComponent);
    onRowClick(row: any, event: any): void;
    onRowDblClick(row: any, event: any): void;
    onRowContextMenu(row: any, event: any): void;
    onCellClick(row: any, col: any, rowEl: any, cellEl: any, event: any): void;
    onCellDblClick(row: any, col: any, rowEl: any, cellEl: any, event: any): void;
    onCellContextMenu(row: any, col: any, event: any): void;
    doEdit(row: any, col: any, rowEl: any, cellEl: any): void;
    onCellKeyDown(row: any, col: any, cell: any, event: any): void;
    onGroupExpanderClick(value: any, event: any): void;
    onDetailExpanderClick(row: any, event: any): void;
    getRowIndex(rowIndex: number): any;
    getCss(css: any, row: any, value: any, type: string): any;
    getRowClass(row: any): any;
    getRowStyle(row: any): any;
    getCellClass(column: any, row: any): any;
    getCellStyle(column: any, row: any): any;
    isEditable(row: any, col: any): boolean;
}
