import { QueryList, EventEmitter } from '@angular/core';
import { PaginationComponent } from '../pagination/pagination.component';
import { PageTemplateDirective } from '../base/template-base';
export declare class ListBaseComponent {
    pageTemplate: PageTemplateDirective;
    pageRefs: QueryList<PaginationComponent>;
    border: boolean;
    loading: boolean;
    loadMsg: string;
    pagination: boolean;
    pagePosition: string;
    pageOptions: any;
    lazy: boolean;
    virtualScroll: boolean;
    rowHeight: number;
    pageNumber: number;
    pageSize: number;
    total: number;
    idField: string;
    selectionMode: string;
    selectionChange: EventEmitter<{}>;
    pageChange: EventEmitter<{}>;
    rowSelect: EventEmitter<{}>;
    rowUnselect: EventEmitter<{}>;
    rowClick: EventEmitter<{}>;
    cellSelect: EventEmitter<{}>;
    cellUnselect: EventEmitter<{}>;
    cellClick: EventEmitter<{}>;
    _initialized: boolean;
    pageState: any;
    highlightRow: any;
    highlightCell: any;
    selectedRows: any[];
    selectedCells: any[];
    rows: any[];
    _data: any[];
    selection: any;
    data: any[];
    ngOnInit(): void;
    ngAfterContentInit(): void;
    ngAfterViewInit(): void;
    setData(value: any[]): void;
    onPageChange(event: any): void;
    onVirtualPageChange(event: any): void;
    onRowClick(row: any, event: any): void;
    onCellClick(row: any, column: any, event: any): void;
    sortData(): void;
    doEnter(): void;
    getSelectedIndex(row: any): number;
    getSelectedCellIndex(row: any, column: any): number;
    isCellSelectionMode(): boolean;
    isHighlighted(row: any, column?: any): boolean;
    isSelected(row: any, column?: any): boolean;
    selectRow(row: any): void;
    unselectRow(row: any): void;
    selectCell(row: any, column: any): void;
    unselectCell(row: any, column: any): void;
    clearSelections(): void;
    navRow(step: number): void;
}
