/**
 * EasyUI for Angular 0.2
 * 
 * Copyright (c) 2009-2017 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: https://www.jeasyui.com/license_freeware2.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
 */
import{Directive,Input,TemplateRef}from"@angular/core";var ItemTemplateDirective=function(){return function(template){this.template=template}}();export{ItemTemplateDirective};ItemTemplateDirective.decorators=[{type:Directive,args:[{selector:"[euiItemTemplate]"}]}],ItemTemplateDirective.ctorParameters=function(){return[{type:TemplateRef}]};var HeaderTemplateDirective=function(){return function(template){this.template=template}}();export{HeaderTemplateDirective};HeaderTemplateDirective.decorators=[{type:Directive,args:[{selector:"[euiHeaderTemplate]"}]}],HeaderTemplateDirective.ctorParameters=function(){return[{type:TemplateRef}]};var CellTemplateDirective=function(){return function(template){this.template=template}}();export{CellTemplateDirective};CellTemplateDirective.decorators=[{type:Directive,args:[{selector:"[euiCellTemplate]"}]}],CellTemplateDirective.ctorParameters=function(){return[{type:TemplateRef}]};var EditTemplateDirective=function(){return function(template){this.template=template}}();export{EditTemplateDirective};EditTemplateDirective.decorators=[{type:Directive,args:[{selector:"[euiEditTemplate]"}]}],EditTemplateDirective.ctorParameters=function(){return[{type:TemplateRef}]};var FooterTemplateDirective=function(){return function(template){this.template=template}}();export{FooterTemplateDirective};FooterTemplateDirective.decorators=[{type:Directive,args:[{selector:"[euiFooterTemplate]"}]}],FooterTemplateDirective.ctorParameters=function(){return[{type:TemplateRef}]};var GroupTemplateDirective=function(){return function(template){this.template=template}}();export{GroupTemplateDirective};GroupTemplateDirective.decorators=[{type:Directive,args:[{selector:"[euiGroupTemplate]"}]}],GroupTemplateDirective.ctorParameters=function(){return[{type:TemplateRef}]},GroupTemplateDirective.propDecorators={groupCls:[{type:Input}],groupStyle:[{type:Input}]};var DetailTemplateDirective=function(){return function(template){this.template=template,this.height=null}}();export{DetailTemplateDirective};DetailTemplateDirective.decorators=[{type:Directive,args:[{selector:"[euiDetailTemplate]"}]}],DetailTemplateDirective.ctorParameters=function(){return[{type:TemplateRef}]},DetailTemplateDirective.propDecorators={height:[{type:Input}]};var PageTemplateDirective=function(){return function(template){this.template=template}}();export{PageTemplateDirective};PageTemplateDirective.decorators=[{type:Directive,args:[{selector:"[euiPageTemplate]"}]}],PageTemplateDirective.ctorParameters=function(){return[{type:TemplateRef}]};