import { Renderer2, ElementRef, EventEmitter, ChangeDetectorRef } from '@angular/core';
export declare class VirtualScrollComponent {
    cdRef: ChangeDetectorRef;
    render: Renderer2;
    bodyRef: ElementRef;
    topRef: ElementRef;
    bottomRef: ElementRef;
    contentRef: ElementRef;
    width: any;
    minWidth: any;
    maxWidth: any;
    height: any;
    minHeight: any;
    maxHeight: any;
    lazy: boolean;
    rowHeight: number;
    maxDivHeight: number;
    maxVisibleHeight: number;
    pageNumber: number;
    pageSize: number;
    total: number;
    onUpdate: EventEmitter<{}>;
    onPageChange: EventEmitter<{}>;
    bodyScroll: EventEmitter<{}>;
    private _data;
    data: any[];
    readonly scrollTop: number;
    readonly scrollbarWidth: number;
    items: any[];
    waitingPage: number;
    startIndex: number;
    deltaTopHeight: number;
    topHeights: any[];
    bottomHeights: any[];
    populateTimer: any;
    isUpdating: boolean;
    isNewFetching: boolean;
    constructor(cdRef: ChangeDetectorRef, render: Renderer2);
    ngAfterViewInit(): void;
    scrolling(): void;
    populate(): void;
    splitHeights(height: any): any[];
    loadPage(items: any): void;
    private fetchingPage;
    fetchPage(page: number): void;
    gotoPage(page: number): void;
    refresh(): void;
}
