import { EventEmitter } from '@angular/core';
import { ComboBaseComponent } from '../base/combo-base.component';
import { ItemTemplateDirective } from '../base/template-base';
import { DataListComponent } from '../datalist/datalist.component';
export declare const COMBOBOX_PANEL_TEMPLATE: string;
export declare const COMBOBOX_TEMPLATE: string;
export declare class ComboBoxComponent extends ComboBaseComponent<any> {
    datalist: DataListComponent;
    itemTemplate: ItemTemplateDirective;
    valueField: string;
    textField: string;
    groupField: string;
    limitToList: boolean;
    lazy: boolean;
    virtualScroll: boolean;
    rowHeight: number;
    pageNumber: number;
    pageSize: number;
    total: number;
    selection: any;
    filterChange: EventEmitter<{}>;
    selectionChange: EventEmitter<{}>;
    timer: any;
    mappingTexts: any;
    datalistScrollTop: number;
    inputingText: string;
    displayingText: string;
    lastFilterValue: string;
    items: any;
    _data: any[];
    _text: string;
    data: any[];
    text: string;
    ngAfterContentInit(): void;
    initTextMapping(): void;
    onRowClick(event: any): void;
    onSelectionChange(event: any): void;
    onPageChange(event: any): void;
    onKeyDown(event: any): void;
    onComboBoxBlur(): void;
    fixValue(): void;
    doFilter(value: string): void;
    openPanel(): void;
    closePanel(): void;
    updateText(): void;
    findItem(value: any): any;
    updateSelection(rows: any): void;
    clearSelections(): void;
}
