import { HeaderTemplateDirective, CellTemplateDirective, EditTemplateDirective, FooterTemplateDirective, FilterTemplateDirective } from '../base/template-base';
export declare class GridColumnComponent {
    headerTemplate: HeaderTemplateDirective;
    cellTemplate: CellTemplateDirective;
    editTemplate: EditTemplateDirective;
    footerTemplate: FooterTemplateDirective;
    filterTemplate: FilterTemplateDirective;
    field: string;
    title: string;
    width: any;
    rowspan: number;
    colspan: number;
    sortable: boolean;
    editable: boolean;
    order: string;
    frozen: boolean;
    align: string;
    halign: string;
    sorter: Function;
    headerCls: string;
    headerStyle: Object;
    cellCss: any;
    expander: boolean;
    filterable: boolean;
    filterOperators: string[];
    currOrder: string;
    grid: any;
    _filterOperator: string;
    _filterValue: any;
    _isFiltering: boolean;
    _initialized: boolean;
    filterOperator: string;
    filterValue: any;
    ngOnInit(): void;
    ngAfterViewInit(): void;
}
